In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:


dataframe = pd.read_csv('../data/labelled_dataset_3_topics.csv')
dataframe = dataframe.dropna(how='all')
# can be features other than the text column
features = dataframe["Text"]
labels = dataframe["Best Topic"]
# targets = ["1", "2", "3", "4", "5", "6"]
targets = ["1", "2", "3"]

In [3]:
dataframe

,Platform,Raw,Text,Topic 1,Topic 2,Topic 3,Best Topic
0,Facebook,Why nowadays every thing seem to be increasin...,nowadays every thing seem increasing governanc...,0.960316,0.019696,0.019989,1
1,Facebook,I will have to disagree.. we’re not that high!!,disagree high,0.772866,0.114139,0.112995,1
2,Facebook,"Wag po tayong mag-alala. Naniniwala po ako, is...",tayong magalala naniniwala isusuprise sir bbm ...,0.021459,0.957550,0.020991,2
3,Facebook,Ok lang yang lahat naman nang bansa ganyan. Sa...,ok yang nang bansa ganyan selfish fanatic blen...,0.037489,0.925430,0.037081,2
4,Facebook,Sama-sama tayong BABAON muli.,samasama tayong babaon,0.083516,0.832983,0.083501,2
...,...,...,...,...,...,...,...
4691,Youtube,mukhang nakashabu,mukhang nakashabu,0.111293,0.777430,0.111277,2
4692,Youtube,Bbm is mixed up and confusing on economic terms,bbm mixed confusing economic term,0.881969,0.060535,0.057496,1
4693,Youtube,Mr.utal utal,mrutal utal,0.111413,0.777200,0.111387,2
4694,Youtube,Kung Si Leni Pa Yan \r\n\r\nLutang Na Tayo,leni lutang,0.117132,0.771727,0.111141,2
4695,Youtube,he knowns what to do wag kayo puro kuda wala n...,knowns puro kuda wala maitutulong magtrabaho k...,0.016092,0.967968,0.015940,2

In [4]:
print(dataframe.iloc[0]['Text'])
print(dataframe.iloc[0])

nowadays every thing seem increasing governance control greater good humanity selfish desire power wealth lord bless country
Platform                                               Facebook
Raw           Why nowadays every thing  seem to be increasin...
Text          nowadays every thing seem increasing governanc...
Topic 1                                                0.960316
Topic 2                                                0.019696
Topic 3                                                0.019989
Best Topic                                                    1
Name: 0, dtype: object

In [5]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [6]:
term_to_topic_df = pd.read_csv('../data/term_to_topic.csv')
term_to_topic_df

             Term  Topic  Frequency
0           bless      1   0.000430
1           bless      2   0.000165
2         control      1   0.000880
3         control      3   0.000293
4         country      1   0.007572
...           ...    ...        ...
21927      mrutal      2   0.000097
21928        utal      2   0.000097
21929     aaralan      2   0.000097
21930  kakaumpisa      2   0.000097
21931      knowns      2   0.000097

[21932 rows x 3 columns]

In [7]:

def predict_single_text(text,idx):
   topic_n_scores = {}
   
   for i in targets:
      topic_n_scores[int(i)] = 0
   # for topic_n_scores
   for word in text.split(' '):
      for term_ntopic_freq in term_to_topic_df.loc[term_to_topic_df['Term']==word].values.tolist():
         topic_n_scores[term_ntopic_freq[1]]+=term_ntopic_freq[2]
   # print(topic_n_scores)
   # print(np.argmax(list(topic_n_scores.values()))+1)
   output = np.argmax(list(topic_n_scores.values()))+1
   # print(f'Predict {output} vs. Actual {list(y_test)[idx]}')
   return output



def predict(X_test)->list:
   output = []
   for i,text in enumerate(list(X_test)):
      output.append(predict_single_text(text, i))
   
   return output

In [8]:
predictions = predict(X_test=X_test)
score = accuracy_score(predictions, list(y_test))

print("Rule Based Accuracy Score -> ", score)

Rule Based Accuracy Score ->  0.8553191489361702